### ISSUE TITLE
not working when offline

### ISSUE THREAD

**Issue by maysam** [abhi12299/website#10]
I am running your app with ``` yarn start ``` and I can see the caching statements in the console, but when I disconnect the network, it's not loading an offline version, what am I missing?

**Comment by abhi12299** [comment]
Hey. Thanks for raising the issue. 
The website loads scripts from bootstrap cdn and hence won't work offline in development. However in production build, it caches static assets and hence would work offline there once cached. 
If you still have any issues, feel free to comment

**Comment by maysam** [comment]
sorry for bothering you, the offline capability only works over https, correct or not?

just doing ```yarn build & yarn start``` is not enough? it has to be on a server? like heroku?

**Comment by abhi12299** [comment]
The service worker that caches static assets can only be served on https. However it can also work on localhost

**Comment by maysam** [comment]
so you have tested it and it should work on localhost without https?

**Comment by abhi12299** [comment]
Yes, it works on localhost.
